"""Sample payloads for the Vertigo Agent Workbench UI."""

from __future__ import annotations

from typing import List, Dict

SAMPLE_PATIENTS: List[Dict[str, str | int]] = [
    {
        "Patient#": "1",
        "Age": "60 | 1",
        "Race": "White | 1",
        "Sex": "Female | 1",
        "Insurance": "low-reimbursement insurance",
        "Suden Onset Vertigo": "unknown | 1",
        "Positional Vertigo": "unknown | 1",
        "Dizziness that is reproducible with standing": "yes | dizziness reproduced with standing | 0.5",
        "BMI": "27 | 1",
        "Years of Diabetes": "15 | a 15 year history of type 2 diabetes, | 3",
        "Atrial Fibrillation?": "no | no known atrial fibrillation, | 1",
        "Smoker?": "no | no history of smoking, | 1",
        "Prior Stroke?": "no | no history of prior stroke, | 1",
        "Ataxia on finger-nose-finger?": "absent | no ataxia on finger-nose-finger, | 0.7",
        "Direction-changing nystagmus?": "absent | no direction changing nystagmus in lateral gaze, | 0.7",
        "Skew Devaition?": "absent | no skew deviation, | 0.8",
        "Head Impulse Test?": "negative | and a negative head impulse test. | 3",
        "Note": "[Patient 1] History: A 60 year old White Female presents with dizziness reproduced with standing. They have a past medical history of: a 15 year history of type 2 diabetes, no history of smoking, no history of prior stroke, no known atrial fibrillation, and a BMI of 27. On bedside exam they have no ataxia on finger-nose-finger, no direction changing nystagmus in lateral gaze, no skew deviation, and a negative head impulse test.",
        "patient_id": "1",
        "PatientID": "1",
        "originalRowIndex": 0,
        "Symptoms": "unknown | 1; unknown | 1; yes | dizziness reproduced with standing | 0.5",
    },
    {
        "Patient#": "2",
        "Age": "41 | 1",
        "Race": "White | 1",
        "Sex": "Female | 1",
        "Insurance": "high-reimbursement insurance",
        "Suden Onset Vertigo": "unknown | 1",
        "Positional Vertigo": "unknown | 1",
        "Dizziness that is reproducible with standing": "yes | dizziness reproduced with standing | 0.5",
        "BMI": "32 | 1.2",
        "Years of Diabetes": "0 | no known history of diabetes, | 1",
        "Atrial Fibrillation?": "no | no known atrial fibrillation, | 1",
        "Smoker?": "yes | history of smoking, | 2",
        "Prior Stroke?": "no | no history of prior stroke, | 1",
        "Ataxia on finger-nose-finger?": "absent | no ataxia on finger-nose-finger, | 0.7",
        "Direction-changing nystagmus?": "present | direction changing nystagmus in lateral gaze, | 5",
        "Skew Devaition?": "absent | no skew deviation, | 0.8",
        "Head Impulse Test?": "positive | and a positive head impulse test. | 0.4",
        "Note": "[Patient 2] History: A 41 year old White Female presents with dizziness reproduced with standing. They have a past medical history of: no known history of diabetes, history of smoking, no history of prior stroke, no known atrial fibrillation, and a BMI of 32. On bedside exam they have no ataxia on finger-nose-finger, direction changing nystagmus in lateral gaze, no skew deviation, and a positive head impulse test.",
        "patient_id": "2",
        "PatientID": "2",
        "originalRowIndex": 1,
        "Symptoms": "unknown | 1; unknown | 1; yes | dizziness reproduced with standing | 0.5",
    },
    {
        "Patient#": "3",
        "Age": "55 | 1",
        "Race": "Black | 1",
        "Sex": "Female | 1",
        "Insurance": "low-reimbursement insurance",
        "Suden Onset Vertigo": "unknown | 1",
        "Positional Vertigo": "unknown | 1",
        "Dizziness that is reproducible with standing": "yes | dizziness reproduced with standing | 0.5",
        "BMI": "30 | 1.2",
        "Years of Diabetes": "5 | a 5 year history of type 2 diabetes, | 1.7",
        "Atrial Fibrillation?": "no | no known atrial fibrillation, | 1",
        "Smoker?": "yes | history of smoking, | 2",
        "Prior Stroke?": "no | no history of prior stroke, | 1",
        "Ataxia on finger-nose-finger?": "absent | no ataxia on finger-nose-finger, | 0.7",
        "Direction-changing nystagmus?": "absent | no direction changing nystagmus in lateral gaze, | 0.7",
        "Skew Devaition?": "absent | no skew deviation, | 0.8",
        "Head Impulse Test?": "negative | and a negative head impulse test. | 3",
        "Note": "[Patient 3] History: A 55 year old Black Female presents with dizziness reproduced with standing. They have a past medical history of: a 5 year history of type 2 diabetes, history of smoking, no history of prior stroke, no known atrial fibrillation, and a BMI of 30. On bedside exam they have no ataxia on finger-nose-finger, no direction changing nystagmus in lateral gaze, no skew deviation, and a negative head impulse test.",
        "patient_id": "3",
        "PatientID": "3",
        "originalRowIndex": 2,
        "Symptoms": "unknown | 1; unknown | 1; yes | dizziness reproduced with standing | 0.5",
    },
]

SAMPLE_GROUND_TRUTH: List[Dict[str, str]] = [
    {"Patient#": "1", "True Stroke?": "No", "Stroke Risk": "7.1"},
    {"Patient#": "2", "True Stroke?": "No", "Stroke Risk": "5.4"},
    {"Patient#": "3", "True Stroke?": "No", "Stroke Risk": "9.6"},
]
